### ISSUE TITLE
Bug in removing duplicate paths

### ISSUE THREAD

**Issue by denibertovic** [fpco/cache-s3#9]
When we remove duplicate paths [here](https://github.com/fpco/cache-s3/blob/master/src/Network/AWS/S3/Cache/Local.hs#L46) we're not taking into account a situation where we might want to save two folders like `.ghc` and `.ghcjs`. The sort functions will sort this as `[".ghc", ".ghcjs"]` (so it doesn't matter how we order it) and will then conclude that `.ghcjs` is a subpath of `.ghc` and will therefore not cache it. I'm guessing there are other valid examples but this is one that I just ran into.

**Comment by lehins** [comment]
@denibertovic great find :) I think the proper solution to this would be to do `splitPath` and then do prefix filtering the same way it is now, but on the list of lists. Do you see any problems with that approach?

**Comment by denibertovic** [comment]
@lehins I think that would work. :+1: Probably worth writing a test case for it as well.

**Comment by lehins** [comment]
@denibertovic Finally was able to get to this ticket. I'll make a new release `v0.1.5` in a little bit.
While fixing this problem also noticed that on Windows `[".ghc", ".GHC"]` wouldn't get filtered out and would be included twice, which is now fixed too. Added some test cases as well, as requested ;)
